### PR TITLE
Incorporate Parthenon Uniform Cartesian Cleanup

### PR DESCRIPTION
**Pull request by forrestglines**
Draft PR to reflect potential cleanup for uniform Cartesian

### CODE REVIEW

**Comment by pgrete** [comment]
@forrestglines do you want to update this PR or should I open a new one?
I'd like to bump Parthenon to https://github.com/parthenon-hpc-lab/parthenon/pull/805 and Kokkos to 3.7.01 to fix the issues with HIP (cf the update I made today to parthenon-hydro, see https://github.com/parthenon-hpc-lab/parthenon-hydro/pull/4 ).

I'd like to make these changes first, then merge the new `main` into the AGN triggering PR and then go from there.
Does this sound like a plan?

**Comment by forrestglines** [comment]
@pgrete   I've forced pushed the new changes for Uniform Cartesian and changes for the new boundary-in-one tasks in Parthenon.

Unfortunately, I'm not sure I've done the correct changes for the boundary-on-one tasks, the regression tests are hanging. Can you check if I've made any obvious mistakes?

**Comment by pgrete** [comment]
Looks good. I'll cleanup the task list (i.e., remove the REMOVEME) and replace the `...FA` calls with the templated ones and then merge if CI pass (latter was down as the server restarted and the service doesn't come up automatically -- I should fix that...)

**Comment by pgrete** [comment]
just made the update to the `FA` calls, updated the submodules, cleaned the driver (and fixed a task dependency). So this should be good to go.

**Review by pgrete — APPROVED** [review]

**Pull request merged**
