### PR TITLE
[CI only] reproducer for ascent DataBinning segfault on GPU

### PR DESCRIPTION
**Pull request by BenWibking**
On Delta, this can be built with:
```
mkdir build; cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja -DAscent_DIR=/projects/cvz/bwibking/ascent/install/ascent-develop/lib/cmake/ascent -DPARTHENON_ENABLE_PYTHON_MODULE_CHECK=OFF -DPARTHENON_ENABLE_ASCENT=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_AMPERE80=ON
ninja -j8
```

### CODE REVIEW

**Comment by BenWibking** [comment]
The output for each GPU looks like this:
```
Loguru caught a signal: SIGSEGV
Stack trace:
14            0x45622e ./build-gpu/bin/athenaPK() [0x45622e]
13      0x7f1d8795b493 __libc_start_main + 243
12            0x44113f ./build-gpu/bin/athenaPK() [0x44113f]
11            0x6cf411 ./build-gpu/bin/athenaPK() [0x6cf411]
10            0x7775de ./build-gpu/bin/athenaPK() [0x7775de]
9             0x85b1d8 ./build-gpu/bin/athenaPK() [0x85b1d8]
8       0x7f1dac228707 ascent::Ascent::execute(conduit::Node const&) + 439
7       0x7f1dac252d30 ascent::AscentRuntime::Execute(conduit::Node const&) + 1072
6       0x7f1dabef00d1 flow::Workspace::execute() + 817
5       0x7f1dac410500 ascent::runtime::filters::BasicQuery::execute() + 672
4       0x7f1dac26a8ed ascent::runtime::expressions::ExpressionEval::evaluate(std::string, std::string) + 2717
3       0x7f1dabef00d1 flow::Workspace::execute() + 817
2       0x7f1dac322f8e ascent::runtime::expressions::Binning::execute() + 846
1       0x7f1dac322066 ascent::runtime::expressions::binning_interface(std::string const&, std::string const&, conduit::Node const&, conduit::Node const&, conduit::Node const&, conduit::Node&, conduit::Node&, conduit::Node&) + 2454
0       0x7f1dac29227b ascent::runtime::expressions::binning(conduit::Node const&, conduit::Node&, std::string const&, std::string const&, double, std::string const&) + 6875
2023-03-31 10:36:22.940 (   2.472s) [main thread     ]                       :0     FATL| Signal: SIGSEGV
```

**Comment by nicolemarsaglia** [comment]
Can I get some coaching on how to build this reproducer? For instance, what is Delta and how do I access it? Thanks!

**Comment by BenWibking** [comment]
> Can I get some coaching on how to build this reproducer? For instance, what is Delta and how do I access it? Thanks!

Ah, sorry, Delta is a machine at NCSA. It may not be easily possible to get access. You can build this from this branch (https://github.com/BenWibking/athenapk/tree/ascent-reproducer-databinning) on another machine, or I can try building this on Crusher and see if I can reproduce it there.

**Comment by nicolemarsaglia** [comment]
> > Can I get some coaching on how to build this reproducer? For instance, what is Delta and how do I access it? Thanks!
> 
> Ah, sorry, Delta is a machine at NCSA. It may not be easily possible to get access. You can build this from this branch (https://github.com/BenWibking/athenapk/tree/ascent-reproducer-databinning) on another machine, or I can try building this on Crusher and see if I can reproduce it there.

Yeah, after some light digging it looks like I probably cannot get on Delta without preparing a proposal for requesting access. Crusher is probably the best course of action.

**Comment by BenWibking** [comment]
This runs perfectly fine on Frontier. I will try to reproduce the error on Summit.

**Comment by BenWibking** [comment]
Since this is caused by a design issue in Ascent (namely, assuming that unified memory is always available), I am closing this.

**Pull request closed without merging**
